server:
  port: 8080

spring:
  cloud:
    compatibility-verifier:
      enabled: false
    gateway:
      default-filters:
        - RemoveRequestHeader=Cookie
      routes:
        - id: auth-service
          uri: http://localhost:8081
          predicates:
            - Path=/auth/**

        - id: hotel-service
          uri: http://localhost:8082
          predicates:
            - Path=/hotels/**, /rooms/**

        - id: reservation-service
          uri: http://localhost:8083
          predicates:
            - Path=/reservations/**

        - id: notification-service
          uri: http://localhost:8084
          predicates:
            - Path=/notifications/**

main:
  web-application-type: reactive

jwt:
  secret: MyUltraSecureKeyThatIsVeryLong 